// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoxowyyzmklzkmskuxrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFveG93eXl6bWtsemttc2t1eHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODY1MDQsImV4cCI6MjA2OTU2MjUwNH0.xhPV8Oof11OJsNTR9Yt1ZnJFhc_2E5mZrUIhSDGXyoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});